class JsonResponseSimulator {
  static Map<String, dynamic> profile = {
    "id": 4,
    "username": "test2",
    "name": "changed",
    "first_name": "changed",
    "last_name": "changed",
    "email": "changed@gmail.com",
    "url": "http://changed%202",
    "description": "changed",
    "link": "https://localhost/wordpress_test/author/changed/",
    "locale": "fa_IR",
    "nickname": "changed",
    "slug": "changed",
    "roles": ["administrator"],
    "registered_date": "2024-10-16T13:42:03+00:00",
    "capabilities": {
      "switch_themes": true,
      "edit_themes": true,
      "activate_plugins": true,
      "edit_plugins": true,
      "edit_users": true,
      "edit_files": true,
      "manage_options": true,
      "moderate_comments": true,
      "manage_categories": true,
      "manage_links": true,
      "upload_files": true,
      "import": true,
      "unfiltered_html": true,
      "edit_posts": true,
      "edit_others_posts": true,
      "edit_published_posts": true,
      "publish_posts": true,
      "edit_pages": true,
      "read": true,
      "level_10": true,
      "level_9": true,
      "level_8": true,
      "level_7": true,
      "level_6": true,
      "level_5": true,
      "level_4": true,
      "level_3": true,
      "level_2": true,
      "level_1": true,
      "level_0": true,
      "edit_others_pages": true,
      "edit_published_pages": true,
      "publish_pages": true,
      "delete_pages": true,
      "delete_others_pages": true,
      "delete_published_pages": true,
      "delete_posts": true,
      "delete_others_posts": true,
      "delete_published_posts": true,
      "delete_private_posts": true,
      "edit_private_posts": true,
      "read_private_posts": true,
      "delete_private_pages": true,
      "edit_private_pages": true,
      "read_private_pages": true,
      "delete_users": true,
      "create_users": true,
      "unfiltered_upload": true,
      "edit_dashboard": true,
      "update_plugins": true,
      "delete_plugins": true,
      "install_plugins": true,
      "update_themes": true,
      "install_themes": true,
      "update_core": true,
      "list_users": true,
      "remove_users": true,
      "promote_users": true,
      "edit_theme_options": true,
      "delete_themes": true,
      "export": true,
      "administrator": true
    },
    "extra_capabilities": {"administrator": true},
    "avatar_urls": {
      "24":
          "https://secure.gravatar.com/avatar/246ece844011faeec5d133e9f73d150a?s=24&d=mm&r=g",
      "48":
          "https://secure.gravatar.com/avatar/246ece844011faeec5d133e9f73d150a?s=48&d=mm&r=g",
      "96":
          "https://secure.gravatar.com/avatar/246ece844011faeec5d133e9f73d150a?s=96&d=mm&r=g"
    },
    "meta": {"persisted_preferences": []},
    "acf": {"book": false},
    "_links": {
      "self": [
        {"href": "https://localhost/wordpress_test/wp-json/wp/v2/users/4"}
      ],
      "collection": [
        {"href": "https://localhost/wordpress_test/wp-json/wp/v2/users"}
      ]
    }
  };
}
