name: Custom Workflow

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check If icov.info exists
        run: |
          if [ -f "./coverage/lcov.info" ]; then
            echo "file_exists=true" >> $GITHUB_ENV
          else
            echo "file_exists=false" >> $GITHUB_ENV
          fi

      - name: Parse coverage percentage from lcov.info
        if: env.file_exists == 'true'
        run: |
          total_lines=$(grep -Po 'LF:\d+' coverage/lcov.info | awk -F':' '{sum += $2} END {print sum}')
          covered_lines=$(grep -Po 'LH:\d+' coverage/lcov.info | awk -F':' '{sum += $2} END {print sum}')
          if [ "$total_lines" -gt 0 ]; then
            coverage_percentage=$(echo "scale=2; $covered_lines * 100 / $total_lines" | bc)
            echo "$coverage_percentage" > coverage_percentage.txt
          else
            echo "0.00" > coverage_percentage.txt
          fi

      - name: Commit Coverage Percentage
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"


          git add coverage_percentage.txt
          git commit -m "Add coverage percentage file"


          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
